import type { Metadata } from 'next';
import Link from 'next/link';
import SiteHeader from '@/components/layout/site-header';
import SiteFooter from '@/components/layout/site-footer';
import {
  generateBreadcrumbSchema,
  wrapInGraph,
} from '@/lib/utils/structured-data';

export const metadata: Metadata = {
  title: 'Statement of Faith — GoFish.Life',
  description:
    'The foundational beliefs that guide GoFish.Life: Scripture authority, the nature of God, salvation through grace, the role of prayer, and our interdenominational approach.',
  openGraph: {
    title: 'Statement of Faith — GoFish.Life',
    description:
      'The foundational beliefs that guide GoFish.Life and its Scripture-based prayer responses.',
    url: 'https://gofish.life/about/statement-of-faith',
  },
  alternates: {
    canonical: 'https://gofish.life/about/statement-of-faith',
  },
};

export default function StatementOfFaithPage() {
  const breadcrumbSchema = generateBreadcrumbSchema([
    { name: 'Home', url: 'https://gofish.life' },
    { name: 'About', url: 'https://gofish.life/about' },
    {
      name: 'Statement of Faith',
      url: 'https://gofish.life/about/statement-of-faith',
    },
  ]);

  return (
    <div className="max-w-[720px] mx-auto px-5 pt-8 pb-16">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(wrapInGraph([breadcrumbSchema])),
        }}
      />
      <SiteHeader />

      <nav
        aria-label="Breadcrumb"
        className="text-[0.82rem] text-[var(--ink-subtle)] mt-4 mb-6"
      >
        <Link
          href="/"
          className="text-oceanblue hover:text-seateal transition-colors"
        >
          Home
        </Link>
        <span className="mx-2">/</span>
        <Link
          href="/about"
          className="text-oceanblue hover:text-seateal transition-colors"
        >
          About
        </Link>
        <span className="mx-2">/</span>
        <span>Statement of Faith</span>
      </nav>

      <h1 className="font-serif font-semibold text-3xl mt-0 mb-2 tracking-tight">
        Statement of Faith
      </h1>
      <p className="text-[var(--ink-muted)] mb-8 text-[0.95rem]">
        The foundational beliefs that guide every prayer response on
        GoFish.Life.
      </p>

      <section className="card mb-6">
        <h2 className="text-lg font-bold mb-3 tracking-tight">
          Scripture as Authority
        </h2>
        <p className="text-[var(--ink-muted)] text-[0.95rem] leading-relaxed m-0">
          We believe the Bible is the inspired Word of God and the ultimate
          authority for faith and life. Every prayer response generated by
          GoFish.Life is rooted in Scripture. Bible verses are selected for
          relevance to each user&apos;s concern, and interpretations aim to be
          faithful to the text in its original context.
        </p>
      </section>

      <section className="card mb-6">
        <h2 className="text-lg font-bold mb-3 tracking-tight">
          The Nature of God
        </h2>
        <p className="text-[var(--ink-muted)] text-[0.95rem] leading-relaxed m-0">
          We believe in one God who exists eternally as Father, Son, and Holy
          Spirit. God is loving, just, merciful, and sovereign. He invites every
          person into a relationship with Him through prayer, and He hears the
          prayers of all who call on Him.
        </p>
      </section>

      <section className="card mb-6">
        <h2 className="text-lg font-bold mb-3 tracking-tight">
          Salvation Through Grace
        </h2>
        <p className="text-[var(--ink-muted)] text-[0.95rem] leading-relaxed m-0">
          We believe that salvation is a gift of God&apos;s grace, received
          through faith in Jesus Christ. It is not earned by human effort but
          given freely to all who believe. This grace is the foundation of the
          hope and encouragement we seek to share through GoFish.Life.
        </p>
      </section>

      <section className="card mb-6">
        <h2 className="text-lg font-bold mb-3 tracking-tight">
          The Role of Prayer
        </h2>
        <p className="text-[var(--ink-muted)] text-[0.95rem] leading-relaxed m-0">
          We believe prayer is a vital part of the Christian life &mdash; a
          direct line of communication with God. Prayer is not a formula but a
          relationship. GoFish.Life exists to help people approach God with
          honesty, grounded in the promises of His Word, whether they are
          seasoned believers or exploring faith for the first time.
        </p>
      </section>

      <section className="card mb-6">
        <h2 className="text-lg font-bold mb-3 tracking-tight">
          Interdenominational Approach
        </h2>
        <p className="text-[var(--ink-muted)] text-[0.95rem] leading-relaxed m-0">
          GoFish.Life is not affiliated with any specific church, denomination,
          or theological tradition. Our prayer responses are grounded in
          Scripture and aim to be faithful to the Bible without promoting a
          particular denominational perspective. We welcome users from all
          Christian backgrounds and those exploring the Christian faith.
        </p>
      </section>

      <p className="text-[0.9rem] text-[var(--ink-muted)]">
        <Link
          href="/about"
          className="text-oceanblue hover:text-seateal transition-colors"
        >
          &larr; Back to About
        </Link>
        <span className="mx-3">|</span>
        <Link
          href="/about/editorial-policy"
          className="text-oceanblue hover:text-seateal transition-colors"
        >
          Editorial Policy &rarr;
        </Link>
      </p>

      <SiteFooter />
    </div>
  );
}
