import Link from 'next/link';

export default function TrustSection() {
  return (
    <section className="py-16">
      <p className="text-[0.8rem] font-semibold tracking-[0.06em] uppercase text-coral mb-2">
        Honest and open
      </p>
      <h2 className="font-serif font-semibold text-[clamp(1.5rem,3vw,2.25rem)] tracking-tight m-0 mb-8">
        Built on trust and transparency
      </h2>

      <div className="grid grid-cols-3 gap-4 max-[900px]:grid-cols-1">
        <div className="card">
          <h3 className="text-[1rem] font-bold m-0 mb-2 tracking-tight text-seateal">
            Bible text from YouVersion
          </h3>
          <p className="m-0 text-[0.9rem] text-[var(--ink-muted)] leading-relaxed">
            Every verse is sourced directly from the YouVersion Platform SDK,
            the same trusted library behind the Bible App used by hundreds of millions.
          </p>
        </div>

        <div className="card">
          <h3 className="text-[1rem] font-bold m-0 mb-2 tracking-tight text-seateal">
            AI-assisted, Scripture-grounded
          </h3>
          <p className="m-0 text-[0.9rem] text-[var(--ink-muted)] leading-relaxed">
            Responses are generated by AI trained to follow pastoral care principles.
            Every answer is rooted in Scripture, not opinion.
          </p>
        </div>

        <div className="card">
          <h3 className="text-[1rem] font-bold m-0 mb-2 tracking-tight text-seateal">
            Not a substitute for professional help
          </h3>
          <p className="m-0 text-[0.9rem] text-[var(--ink-muted)] leading-relaxed">
            GoFish.Life is not pastoral, medical, legal, or emergency advice.
            Please reach out to a pastor, counselor, doctor, or emergency services when appropriate.
          </p>
        </div>
      </div>

      <div className="mt-6 text-center">
        <Link
          href="/transparency"
          className="text-oceanblue no-underline border-b border-oceanblue/35 hover:text-seateal hover:border-seateal transition-colors text-[0.9rem]"
        >
          Read our full transparency statement
        </Link>
      </div>
    </section>
  );
}
