import type { Metadata } from 'next';
import Link from 'next/link';
import SiteHeader from '@/components/layout/site-header';
import SiteFooter from '@/components/layout/site-footer';
import {
  generateBreadcrumbSchema,
  wrapInGraph,
} from '@/lib/utils/structured-data';

export const metadata: Metadata = {
  title: 'Terms of Service — GoFish.Life',
  description:
    'Terms of service for using GoFish.Life, a free Scripture-based prayer response platform.',
  openGraph: {
    title: 'Terms of Service — GoFish.Life',
    description: 'Terms of service for using GoFish.Life.',
    url: 'https://gofish.life/terms',
  },
  alternates: {
    canonical: 'https://gofish.life/terms',
  },
};

export default function TermsPage() {
  const breadcrumbSchema = generateBreadcrumbSchema([
    { name: 'Home', url: 'https://gofish.life' },
    { name: 'Terms of Service', url: 'https://gofish.life/terms' },
  ]);

  return (
    <div className="max-w-[720px] mx-auto px-5 pt-8 pb-16">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(wrapInGraph([breadcrumbSchema])),
        }}
      />
      <SiteHeader />

      <nav
        aria-label="Breadcrumb"
        className="text-[0.82rem] text-[var(--ink-subtle)] mt-4 mb-6"
      >
        <Link
          href="/"
          className="text-oceanblue hover:text-seateal transition-colors"
        >
          Home
        </Link>
        <span className="mx-2">/</span>
        <span>Terms of Service</span>
      </nav>

      <h1 className="font-serif font-semibold text-3xl mt-0 mb-2 tracking-tight">
        Terms of Service
      </h1>
      <p className="text-[var(--ink-muted)] mb-8 text-[0.95rem]">
        By using GoFish, you agree to the following terms.
      </p>

      <section className="card mb-6">
        <h2 className="text-lg font-bold mb-3 tracking-tight">
          Acceptance of Terms
        </h2>
        <p className="text-[var(--ink-muted)] text-[0.95rem] leading-relaxed m-0">
          By accessing or using GoFish, you agree to be bound by these Terms of
          Service. If you do not agree to these terms, please do not use the
          service.
        </p>
      </section>

      <section className="card mb-6">
        <h2 className="text-lg font-bold mb-3 tracking-tight">
          Description of Service
        </h2>
        <p className="text-[var(--ink-muted)] text-[0.95rem] leading-relaxed m-0">
          GoFish is an AI-assisted prayer and Scripture encouragement tool. You
          submit a prayer request or concern, and the service returns relevant
          Bible verses, faithful interpretation, practical guidance, and a
          prayer grounded in God&apos;s Word.
        </p>
      </section>

      <section className="card mb-6">
        <h2 className="text-lg font-bold mb-3 tracking-tight">
          User Accounts
        </h2>
        <p className="text-[var(--ink-muted)] text-[0.95rem] leading-relaxed m-0">
          Some features require creating an account. You are responsible for
          maintaining the confidentiality of your account credentials and for
          all activity that occurs under your account.
        </p>
      </section>

      <section className="card mb-6">
        <h2 className="text-lg font-bold mb-3 tracking-tight">
          Acceptable Use
        </h2>
        <p className="text-[var(--ink-muted)] text-[0.95rem] leading-relaxed m-0">
          You agree not to misuse GoFish. This includes but is not limited to:
          submitting harmful, abusive, or illegal content; attempting to
          circumvent content moderation; using the service for automated or
          bulk requests; or interfering with the operation of the service.
        </p>
      </section>

      <section className="card mb-6">
        <h2 className="text-lg font-bold mb-3 tracking-tight">
          AI-Generated Content
        </h2>
        <p className="text-[var(--ink-muted)] text-[0.95rem] leading-relaxed m-0">
          Responses are generated by artificial intelligence and are provided
          for spiritual encouragement only. They do not constitute
          professional counseling, legal advice, medical guidance, or
          authoritative theological instruction. You should exercise your own
          judgment when applying any content from GoFish.
        </p>
      </section>

      <section className="card mb-6">
        <h2 className="text-lg font-bold mb-3 tracking-tight">
          Intellectual Property
        </h2>
        <p className="text-[var(--ink-muted)] text-[0.95rem] leading-relaxed m-0">
          Bible verse text is provided by YouVersion and is subject to its
          respective copyright and usage terms. All other content, design, and
          code comprising GoFish are the property of their respective owners.
        </p>
      </section>

      <section className="card mb-6">
        <h2 className="text-lg font-bold mb-3 tracking-tight">
          Disclaimer of Warranties
        </h2>
        <p className="text-[var(--ink-muted)] text-[0.95rem] leading-relaxed m-0">
          GoFish is provided &ldquo;as is&rdquo; and &ldquo;as
          available&rdquo; without warranties of any kind, either express or
          implied. We do not guarantee the accuracy, completeness, or
          reliability of any AI-generated content.
        </p>
      </section>

      <section className="card mb-6">
        <h2 className="text-lg font-bold mb-3 tracking-tight">
          Limitation of Liability
        </h2>
        <p className="text-[var(--ink-muted)] text-[0.95rem] leading-relaxed m-0">
          To the fullest extent permitted by law, GoFish and its operators
          shall not be liable for any indirect, incidental, special,
          consequential, or punitive damages arising from your use of the
          service.
        </p>
      </section>

      <section className="card mb-6">
        <h2 className="text-lg font-bold mb-3 tracking-tight">
          Privacy
        </h2>
        <p className="text-[var(--ink-muted)] text-[0.95rem] leading-relaxed m-0">
          Your use of GoFish is also governed by our{' '}
          <Link
            href="/privacy"
            className="text-oceanblue no-underline border-b border-oceanblue/35 hover:text-seafoam"
          >
            Privacy Policy
          </Link>
          , which describes how we handle your data.
        </p>
      </section>

      <section className="card mb-6">
        <h2 className="text-lg font-bold mb-3 tracking-tight">
          Changes to These Terms
        </h2>
        <p className="text-[var(--ink-muted)] text-[0.95rem] leading-relaxed m-0">
          We may update these terms as the service evolves. Continued use of
          GoFish after changes are posted constitutes acceptance of the
          revised terms. Significant changes will be noted on this page.
        </p>
      </section>

      <SiteFooter />
    </div>
  );
}
